### PR TITLE
Add IOUserClient class to CMake builds, and add fields in kernel

### PR DESCRIPTION
**Pull request by nealsid**
#430 
#433

### CODE REVIEW

**Comment by opcm** [comment]
Thanks for the patch. Sorry, I was out of office. I will try to find someone to review

**Comment by patrickkonsor** [comment]
I would recommend adding a 4 byte padding to the end of the topologyEntry struct to make it 32 bytes.

**Comment by nealsid** [comment]
> I would recommend adding a 4 byte padding to the end of the topologyEntry struct to make it 32 bytes.

Done.

**Review by patrickkonsor — APPROVED** [review]

**Comment by nealsid** [comment]
Ah, I'm running into an error that only shows up in release mode, for the same reason (inconsistency between the struct in cpucounters.h and the user land driver interface wrapper on macOS). Sorry for not catching this, I will send a fix ASAP.

**Pull request merged**
