### PR TITLE
Issue #153 on Windows, Cannot find "thr/xthread"

### PR DESCRIPTION
**Pull request by kvanderlaag**

### CODE REVIEW

**Comment by opcm** [comment]
Where xtime is documented?

**Comment by opcm** [comment]
_Thrd_sleep expects target time (not the duration), so I don't think your change is correct

**Comment by kvanderlaag** [comment]
Certainly not impossible; what was the previous call to `_To_xtime` returning? As far as I could tell, it was simply converting an `std::chrono::microseconds` to an `xtime`.

**Comment by opcm** [comment]
Current time + delay : http://sandbox.hlt.bme.hu/~gaebor/STLdoc/VS2017/chrono.html#a4bf5ff5207c328ebb91543b4eb98122e

**Comment by kvanderlaag** [comment]
Is there a compelling reason not to replace the `xthreads` include with `thread` and use `std::this_thread::sleep_for(std::chrono::microseconds(delay_us));` then?

**Comment by opcm** [comment]
I did some research and found out that neither _Thrd_sleep nor sleep_for provide microsecond granularity on Windows. They all call SleepEx which has only millisecond granularity. But it turned out the only consumer of win_usleep/MySleepUs is pcm-pcie.cpp which needs only millisecond precision. To resolve issue #153 I suggest to drop all microsecond sleep functions and make a change in pcm-pcie.cpp to use MySleepMs.

**Comment by opcm** [comment]
This is fixed here: https://github.com/opcm/pcm/commit/b506758ff58bf1eae95fffd9ca42baeb51f5abbe

**Pull request closed without merging**
