### PR TITLE
Formatting-only changes

### PR DESCRIPTION
**Pull request by nealsid**
I went through some of the macOS files (not all) and made some changes to
make it more consistent with code in other platforms.

- Removed whitespace-only lines and trailing whitespace
- Moved braces to new lines
- Removed tabs
- Set indent to 4 spaces

I didn't put time into making it automated as I wasn't sure of the exact rules.  Thanks.

### CODE REVIEW

**Comment by opcm** [comment]
sorry, I do not see enough value in formatting-only changes (and also potential discussions on individual preferences which might result from such changes/proposals).

**Comment by nealsid** [comment]
Thanks! I don't suppose you'd mind making an exception in this case?  

I can definitely update the formatting as I make other changes, but the reason doing it separately is helpful is that when going through the history of changes, my experience is that it's easier if functional changes are not interspersed with formatting changes (in this case, the code in the MacMSR directory seems to have an inconsistent and platform-specific style applied throughout).  Also, I'm not particular to any style, and would rather just be consistent with the existing codebase.  

If not, no problem at all, it's just a large amount of changes that will accompany (and distract from) subsequent patches.

**Comment by opcm** [comment]
For me personally it is much easier to review commits which change a few code lines adding/improving functionality or code quality and simultaneously improve formatting of the same code lines. I think we need to better document contributing guidelines in PCM (I like this guide as an example: https://github.com/simdjson/simdjson/blob/master/CONTRIBUTING.md)

**Comment by nealsid** [comment]
Sounds great, thank you! I'll fold these changes into subsequent patches.

**Pull request closed without merging**
